/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as PagoCanceladoRouteImport } from './routes/pago-cancelado'
import { Route as PagoListoRouteImport } from './routes/pago-listo'
import { Route as PagoProblemaRouteImport } from './routes/pago-problema'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as ApiPublicJobsRunRouteImport } from './routes/api/public/jobs/run'
import { Route as ApiPublicPaypalReturnRouteImport } from './routes/api/public/paypal/return'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal/webhook'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoCanceladoRoute = PagoCanceladoRouteImport.update({
  id: '/pago-cancelado',
  path: '/pago-cancelado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoListoRoute = PagoListoRouteImport.update({
  id: '/pago-listo',
  path: '/pago-listo',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoProblemaRoute = PagoProblemaRouteImport.update({
  id: '/pago-problema',
  path: '/pago-problema',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicJobsRunRoute = ApiPublicJobsRunRouteImport.update({
  id: '/api/public/jobs/run',
  path: '/api/public/jobs/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalReturnRoute = ApiPublicPaypalReturnRouteImport.update({
  id: '/api/public/paypal/return',
  path: '/api/public/paypal/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal/webhook',
  path: '/api/public/paypal/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/pago-cancelado': typeof PagoCanceladoRoute
  '/pago-listo': typeof PagoListoRoute
  '/pago-problema': typeof PagoProblemaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/pago-cancelado': typeof PagoCanceladoRoute
  '/pago-listo': typeof PagoListoRoute
  '/pago-problema': typeof PagoProblemaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/pago-cancelado': typeof PagoCanceladoRoute
  '/pago-listo': typeof PagoListoRoute
  '/pago-problema': typeof PagoProblemaRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/pago-cancelado'
    | '/pago-listo'
    | '/pago-problema'
    | '/biblioteca'
    | '/api/public/jobs/run'
    | '/api/public/paypal/return'
    | '/api/public/paypal/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/pago-cancelado'
    | '/pago-listo'
    | '/pago-problema'
    | '/biblioteca'
    | '/api/public/jobs/run'
    | '/api/public/paypal/return'
    | '/api/public/paypal/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceso'
    | '/pago-cancelado'
    | '/pago-listo'
    | '/pago-problema'
    | '/_authenticated/biblioteca'
    | '/api/public/jobs/run'
    | '/api/public/paypal/return'
    | '/api/public/paypal/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesoRoute: typeof AccesoRoute
  PagoCanceladoRoute: typeof PagoCanceladoRoute
  PagoListoRoute: typeof PagoListoRoute
  PagoProblemaRoute: typeof PagoProblemaRoute
  ApiPublicJobsRunRoute: typeof ApiPublicJobsRunRoute
  ApiPublicPaypalReturnRoute: typeof ApiPublicPaypalReturnRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago-cancelado': {
      id: '/pago-cancelado'
      path: '/pago-cancelado'
      fullPath: '/pago-cancelado'
      preLoaderRoute: typeof PagoCanceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago-listo': {
      id: '/pago-listo'
      path: '/pago-listo'
      fullPath: '/pago-listo'
      preLoaderRoute: typeof PagoListoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago-problema': {
      id: '/pago-problema'
      path: '/pago-problema'
      fullPath: '/pago-problema'
      preLoaderRoute: typeof PagoProblemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/jobs/run': {
      id: '/api/public/jobs/run'
      path: '/api/public/jobs/run'
      fullPath: '/api/public/jobs/run'
      preLoaderRoute: typeof ApiPublicJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/return': {
      id: '/api/public/paypal/return'
      path: '/api/public/paypal/return'
      fullPath: '/api/public/paypal/return'
      preLoaderRoute: typeof ApiPublicPaypalReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/webhook': {
      id: '/api/public/paypal/webhook'
      path: '/api/public/paypal/webhook'
      fullPath: '/api/public/paypal/webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesoRoute: AccesoRoute,
  PagoCanceladoRoute: PagoCanceladoRoute,
  PagoListoRoute: PagoListoRoute,
  PagoProblemaRoute: PagoProblemaRoute,
  ApiPublicJobsRunRoute: ApiPublicJobsRunRoute,
  ApiPublicPaypalReturnRoute: ApiPublicPaypalReturnRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
