/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicJobsRunRouteImport } from './routes/api/public/jobs/run'
import { Route as ApiPublicPaypalReturnRouteImport } from './routes/api/public/paypal/return'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal/webhook'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsRunRoute = ApiPublicJobsRunRouteImport.update({
  id: '/api/public/jobs/run',
  path: '/api/public/jobs/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalReturnRoute = ApiPublicPaypalReturnRouteImport.update({
  id: '/api/public/paypal/return',
  path: '/api/public/paypal/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal/webhook',
  path: '/api/public/paypal/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/api/public/paypal/return': typeof ApiPublicPaypalReturnRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/jobs/run'
    | '/api/public/paypal/return'
    | '/api/public/paypal/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/jobs/run'
    | '/api/public/paypal/return'
    | '/api/public/paypal/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/jobs/run'
    | '/api/public/paypal/return'
    | '/api/public/paypal/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicJobsRunRoute: typeof ApiPublicJobsRunRoute
  ApiPublicPaypalReturnRoute: typeof ApiPublicPaypalReturnRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/run': {
      id: '/api/public/jobs/run'
      path: '/api/public/jobs/run'
      fullPath: '/api/public/jobs/run'
      preLoaderRoute: typeof ApiPublicJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/return': {
      id: '/api/public/paypal/return'
      path: '/api/public/paypal/return'
      fullPath: '/api/public/paypal/return'
      preLoaderRoute: typeof ApiPublicPaypalReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/webhook': {
      id: '/api/public/paypal/webhook'
      path: '/api/public/paypal/webhook'
      fullPath: '/api/public/paypal/webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicJobsRunRoute: ApiPublicJobsRunRoute,
  ApiPublicPaypalReturnRoute: ApiPublicPaypalReturnRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
